# Generated by Django 5.2.1 on 2025-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='time_on_activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
