# Generated by Django 5.2.1 on 2025-09-21 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_guardian_time_on_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='days_to_be_contracted',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AddField(
            model_name='child',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
