# Generated by Django 5.2.1 on 2025-09-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_child_days_to_be_contracted_child_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='days_to_be_contracted',
            field=models.JSONField(default=list, max_length=255),
        ),
    ]
