# Generated by Django 5.2.1 on 2025-09-22 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_child_days_to_be_contracted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildmindingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent1_name', models.CharField(max_length=255)),
                ('parent1_address', models.TextField()),
                ('parent1_telephone_home', models.CharField(blank=True, max_length=20, null=True)),
                ('parent1_telephone_work', models.CharField(blank=True, max_length=20, null=True)),
                ('parent1_telephone_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('parent2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent2_address', models.TextField(blank=True, null=True)),
                ('parent2_telephone_home', models.CharField(blank=True, max_length=20, null=True)),
                ('parent2_telephone_work', models.CharField(blank=True, max_length=20, null=True)),
                ('parent2_telephone_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_contact', models.TextField(blank=True, null=True)),
                ('authorised_collectors', models.TextField(help_text='List authorised collectors with addresses and phone numbers')),
                ('collection_password', models.CharField(max_length=255)),
                ('day_fee', models.DecimalField(decimal_places=2, default=45.0, max_digits=6)),
                ('extra_charges', models.TextField(blank=True, help_text='Notes about early/late charges, holidays, sickness rules, etc.', null=True)),
                ('start_date', models.DateField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('parent_signature', models.CharField(max_length=255)),
                ('parent_signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('childminder_signature', models.CharField(default='Laura Oldfield', max_length=255)),
                ('childminder_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='main.child')),
            ],
            options={
                'verbose_name': 'Childminding Contract',
                'verbose_name_plural': 'Childminding Contracts',
            },
        ),
    ]
