# Generated by Django 5.2.1 on 2025-09-22 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_childmindingcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='contract_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
