# Generated by Django 5.2.1 on 2025-09-24 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_child_contract_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmindingcontract',
            name='day_fee',
        ),
        migrations.RemoveField(
            model_name='childmindingcontract',
            name='extra_charges',
        ),
        migrations.RemoveField(
            model_name='childmindingcontract',
            name='review_date',
        ),
        migrations.AddField(
            model_name='childmindingcontract',
            name='day_fee_gbp',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='childmindingcontract',
            name='childminder_signed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='childmindingcontract',
            name='parent_signed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
