# Generated by Django 5.2.1 on 2025-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_childmindingcontract_day_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmindingcontract',
            name='day_fee_gbp',
            field=models.IntegerField(),
        ),
    ]
