# Generated by Django 5.2.1 on 2025-09-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_childmindingcontract_day_fee_gbp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmindingcontract',
            name='childminder_signed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
