# Generated by Django 5.2.1 on 2025-09-26 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_childmindingcontract_childminder_signed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies_signature', models.CharField(max_length=255)),
                ('complaints_signature', models.CharField(max_length=255)),
                ('emergency_signature', models.CharField(max_length=255)),
                ('emergency_caregiver_signature', models.CharField(max_length=255)),
                ('outings_signature', models.CharField(max_length=255)),
                ('photos_signature', models.CharField(max_length=255)),
                ('equipment_signature', models.CharField(max_length=255)),
                ('sharing_signature', models.CharField(max_length=255)),
                ('plaster_signature', models.CharField(max_length=255)),
                ('suncream_signature', models.CharField(max_length=255)),
                ('parent_signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('childminder_signature', models.CharField(default='Laura Oldfield', max_length=255)),
                ('childminder_signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_form', to='main.child')),
            ],
            options={
                'verbose_name': 'Consent Form',
                'verbose_name_plural': 'Consent Forms',
            },
        ),
    ]
