# Generated by Django 5.2.1 on 2025-09-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_consentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='main.child'),
        ),
    ]
