# Generated by Django 5.2.1 on 2025-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_consentform_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='childminder_signed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='parent_signed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
