# Generated by Django 5.2.1 on 2025-09-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_consentform_childminder_signed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consentform',
            old_name='suncream_signature',
            new_name='suncream_wipes_signature',
        ),
        migrations.AddField(
            model_name='consentform',
            name='calpol_signature',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consentform',
            name='firstaid_signature',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consentform',
            name='parent_signature',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consentform',
            name='transport_signature',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
