# Generated by Django 5.2.1 on 2025-09-26 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_suncream_signature_consentform_suncream_wipes_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.TextField()),
                ('languages_spoken', models.CharField(help_text='List main language(s) spoken at home', max_length=255)),
                ('religion_cultural_needs', models.CharField(blank=True, help_text='Optional (e.g. dietary or cultural practices)', max_length=255, null=True)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_surgery', models.CharField(max_length=255)),
                ('doctor_phone', models.CharField(max_length=20)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('dietary_needs', models.TextField(blank=True, null=True)),
                ('medication', models.TextField(blank=True, null=True)),
                ('vaccinations', models.TextField(blank=True, help_text='Optional: vaccination record/confirmation', null=True)),
                ('emergency_contact1_name', models.CharField(max_length=255)),
                ('emergency_contact1_relationship', models.CharField(max_length=255)),
                ('emergency_contact1_phone', models.CharField(max_length=20)),
                ('emergency_contact2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact2_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact2_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='E.g. sleep routines, comfort items, likes/dislikes', null=True)),
                ('parent_signature', models.CharField(max_length=255)),
                ('parent_signed_at', models.DateTimeField(auto_now_add=True)),
                ('parent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('childminder_signature', models.CharField(default='Laura Oldfield', max_length=255)),
                ('childminder_signed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='main.child')),
            ],
        ),
    ]
