# Generated by Django 5.2.1 on 2025-11-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_dailyregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='clock_out',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
