# Generated by Django 5.2.1 on 2026-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_dailyregister_clock_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='clock_in',
            field=models.DateTimeField(),
        ),
    ]
